name: Build SINA AI APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev \
            libtinfo6 cmake libffi-dev libssl-dev \
            automake autopoint gettext

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer setuptools cython==0.29.34

      - name: Prepare Buildozer
        run: |
          sed -i 's/^# *android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
          sed -i 's/^# *p4a.branch = master/p4a.branch = master/' buildozer.spec

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SINA-AI-APK
          path: bin/*.apk
